#!/usr/bin/python3

import socket
import sys
from _thread import *
import select 
import re 

if len(sys.argv)!=3:
    print("the input format should be in ipaddress:portnumber")
    sys.exit()

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
info = (sys.argv[1])
a=info.split(':')
addr=str(a[0])
portn=int(a[1])
nick=str(sys.argv[2])


s.connect((addr, port))

first_msg=s.recv(2048).decode('utf-8')

print(first_msg)

nick = 'NICK ' + nick


s.sendall(nick.encode('utf-8'))

ok_msg=s.recv(2048).decode('utf-8')
print(ok_msg)
if ok_msg == "OK":
    pass
elif ok_msg == "error occured":
    print('nickname is only 12characters without special charaters')
    print('try again by giving valid nickname')
    sys.exit()
    
    



while True:
    socket_list=[sys.stdin, s]
    

    read_sockets,write_sockets,error_sockets=select.select(socket_list,[],[])
    
    for sockets in read_sockets:
        if sockets == s:
            message = sockets.recv(2048).decode('utf-8')
            print(message)
        else:
            message=sys.stdin.readline()
            
            message = 'MSG '+ message
            if message == '\n':
                continue
            else:
                s.sendall(message.encode('utf-8'))
                
s.close()
